# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - youraliasazurepetstoreazat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://youraliasazurepetstorecrazat.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3acf12f8e8864468b74a57a738e97fea }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4fb21c75c07f41ca9cfb02634fc22f65 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: youraliasazurepetstorecrazat.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3acf12f8e8864468b74a57a738e97fea }}/petstoreapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'youraliasazurepetstoreazat'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4241481914bd4d29adc4cf513f5beda6 }}
        images: 'youraliasazurepetstorecrazat.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3acf12f8e8864468b74a57a738e97fea }}/petstoreapp:${{ github.sha }}'